### ISSUE TITLE
Add Action Cache mechanisim

### ISSUE THREAD

**Issue by jfarcand** [vibe-project/vibe-java-server#25]
Similar to the `BroadcasterCache` concept, we need a way to cache messages and resend them (or expose a way for the application).

**Comment by flowersinthesand** [comment]
Because socket is built on top of transport ensuring no message loss, there is no message loss unless the connection is disconnected even with long polling transport. The problem is that while there is no connection whether for a few seconds e.g. switching wifi or weeks e.g. vacation, some events have to be delivered to some real-world entity which was represented by that connection.

The first solution is to cache actions which are supposed to be executed for sockets representing a specific user and to execute them on reconnection like UUIDBroadcasterCache.

1. Each socket should contain identifier tag which is a result of authentication.
    1. identifier tag consisting of one or more tags is used to identify a specific user from the socket set. For example, it could be `/user/donghwan` and `/device/24g0m` (if `24g0m` is device id). And, these tags should correspond exactly one socket like the candidate key from the relational model of database.
    1. How to authenticate depends on each application so that we can't force to compel applications to follow specific way.
    1. If user1 connects to server1, every socket representing user1 should connect to server1 because caching works locally. It's so-called sticky session. With the help of data grid like Hazelcast, the cache may be shared between servers but then Message Oriented Middleware like jGroups can't be used to cluster applications. Moreover, for HTTP transport, sticky session is required to cluster application so it's not big requirement.
1. If socket is opened, its identifier tag is found through authentication. Then, it finds and execute cached actions through the identifier tag by removing them from the cache via server's some method. The cached actions is a group of action which was supposed to be applied to a specific user which this socket is representing.
    1. Finding and executing actions should be done by application developer explicitly. Whether or not to execute some action is developer's decision.
1. Server should retain closed socket for caching action. If server.all or server.byTag is called, the given action is executed immediately for opened socket and the given action is stored to the cache per socket for closed socket. The closed socket is evicted once its successor socket reconnects and retrieves cached actions. If no new connection is established for 1 minute, the closed socket is evicted through server's event. By listening that event, application developer can store actions persistently to execute them later e.g. after a few months or to send emails for notification of missing message.

This is a draft. Also on second thought, even though identifier tag is used, identified socket might be not one if user opens specific page multiple times on the same browser. Therefore, the above idea should be modified or the brand new idea would be needed.

Anyway, tag is a key to associate sockets with the real world entity so that more idea to make use of tag is required and also it should be simple.

**Comment by flowersinthesand** [comment]
> Also on second thought, even though identifier tag is used, identified socket might be not one if user opens specific page multiple times on the same browser.

It tells definite definition of identification and authentication is required. Let's see the following example:

* `socket1` from `donghwan`'s desktop1's chrome1's page1.html
* `socket2` from `donghwan`'s desktop1's chrome1's page2.html
* `socket3` from `donghwan`'s desktop1's firefox1's some page
* `socket4` from `donghwan`'s mobile device1's opera1's some page
* `socket5` from `donghwan`'s desktop2's some application using node client

In terms of authentication, all sockets are `donghwan` so that they can be dealt with the tag name e.g. `/user/donghwan`. In terms of identification, each socket is distinguishable. If `socket5` is closed for network issue and reconnects to the server, new socket, `socket6`, created by `socket5`'s node client should be recognized as `socket5`. Now that `socket6` equals to `socket5`, actions that should have applied to `socket5` during `socket5`'s disconnection can be applied to `socket6` and removed safely.

To do that, socket should have `id`.

* It has nothing to do with tag. The confusion at the first draft solution was because I tried to identify socket using authentication by tag. Identification and authentication are different.
* At first, socket had id property but that id is now transport's id. Therefore, that old id is different with the `id` I say here. Also it should be implemented internally.
* So far socket object in server has had only one life cycle. Now that socket has `id`, it can have repeated life cycle just like socket object in client. This is important inspiration which makes handling socket much easier in server. More research should be done.

Before working on this issue, discussion on socket's `id` should be done first. I'll handle the issue at the protocol level, how to send missing events in not only server but also client. And then, following discussion there, this issue will be handled.

**Comment by flowersinthesand** [comment]
Based on discussion here, https://github.com/vibe-project/vibe-protocol/issues/61, offline application, is created and this feature will be covered according to that issue.
